version: 2

models:
  - name: city
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: id
        description: This is a unique identifier for a customer

      - name: name
        description: Customer's first name. PII.

      - name: district
        description: Customer's last name. PII.

      - name: local_name
        description: Date (UTC) of a customer's first order

      - name: population
        description: Date (UTC) of a customer's most recent order

      - name: country_code
        description: Count of the number of orders a customer has placed

      - name: value
        description: Total value (AUD) of a customer's orders